name: Trigger AWS Amplify Build on Dev Push

on:
    push:
        branches:
            - dev

jobs:
    trigger-aws-amplify-build:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger AWS Amplify Build Hook
              run: curl -X POST -d {} "https://webhooks.amplify.us-east-2.amazonaws.com/prod/webhooks?id=35a54e58-7064-4267-b943-8a68ad0228a9&token=dg2hSmay5mryKpVlUBfMMXbblAGdWMOta3FGqlUGbo&operation=startbuild" -H "Content-Type:application/json"
